spring:
  application:
    name: seats-aero
  datasource:
    url: jdbc:postgresql://localhost:5432/greetings_db
    username: postgres
    password: <password>
    driver-class-name: org.postgresql.Driver
server:
  port: 8081
